openapi: 3.0.3
info:
  title: Topology API
  description: "Documentation about topological relations between geometries."
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1.1
servers:
- url: http://localhost:7206
- url: https://terrain.dd-bim.org
- url: /
paths:
  /topology/relations/graphdbrepo/{repo}:
    get:
      tags:
      - Topology Service
      summary: Compute relationships between geometries from Postgres
      operationId: topology-service
      parameters:
      - name: repo
        in: path
        description: 'The name of the aim graphdb repository. '
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation