minio:
    url: http://terrain.dd-bim.org
    port: 9000
    access_key: AKIAIOSFODNN7EXAMPLE
    secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

postgres:
    url: //terrain.dd-bim.org
    database:
        name: tt
        username: terraintwin
        password: 123456

graphdb:
    url: https://terrain.dd-bim.org/graphdb
    username: graphdb
    password: 123456