version: '3.8'
services:
    configserver:
        container_name: configserver
        image: schi11er/tt_configserver:latest
        restart: unless-stopped
        ports:
            - 8888:8888
        networks:
            - terraintwin_microservices
        volumes:
            - ./volumes/configs:/var/lib/centralProperties
            - ./volumes/logs/:/var/log/
        healthcheck:
            test: wget --spider http://localhost:8888/actuator/health || exit 1
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s
        environment:
            - domain.url=${DOMAIN_URL}

    eurekaserver:
        container_name: eurekaserver
        image: schi11er/tt_eurekaserver:latest
        restart: unless-stopped
        ports:
            - 9091:9091
        networks:
            - terraintwin_microservices
        depends_on: 
            - configserver
        healthcheck:
            test: wget --spider http://localhost:9091/actuator/health || exit 1
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s
        environment:
            - domain.url=${DOMAIN_URL}
        volumes:
            - ./volumes/logs/:/var/log/

    minio-upload-service:
        container_name: minio-upload-service
        image: schi11er/tt_minio-upload-service:latest
        restart: unless-stopped
        ports:
            - 7204:7204
        networks:
            - terraintwin_microservices
        depends_on: 
            - configserver
            - eurekaserver
        healthcheck:
            test: wget --spider http://localhost:7204/actuator/health || exit 1
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s
        environment:
            - domain.url=${DOMAIN_URL}
            - minio.url=${MINIO_URL}
            - minio.port=${MINIO_PORT}
            - minio.access_key=${MINIO_ACCESS_KEY}
            - minio.secret_key=${MINIO_SECRET_KEY}
        volumes:
            - ./volumes/logs/:/var/log/

    file-input-handler:
        container_name: file-input-handler
        image: schi11er/tt_file-input-handler:latest
        restart: unless-stopped
        ports:
            - 7201:7201
        networks:
            - terraintwin_microservices
        depends_on:
            - configserver
            - eurekaserver
        healthcheck:
            test: wget --spider http://localhost:7201/actuator/health || exit 1
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 20s
        environment:
            - domain.url=${DOMAIN_URL}
            - minio.url=${MINIO_URL}
            - minio.port=${MINIO_PORT}
            - minio.access_key=${MINIO_ACCESS_KEY}
            - minio.secret_key=${MINIO_SECRET_KEY}
            - graphdb.url=${GRAPHDB_URL}
            - graphdb.username=${GRAPHDB_USERNAME}
            - graphdb.password=${GRAPHDB_PASSWORD}
        volumes:
            - ./volumes/logs:/var/log
            - ./volumes/configs/repo-config.ttl:/var/config/repo-config.ttl

    geometry-handler:
        container_name: geometry-handler
        image: schi11er/tt_geometry-handler:latest
        restart: unless-stopped
        ports:
            - 7203:7203
        networks:
            - terraintwin_microservices
        depends_on:
            - configserver
            - eurekaserver
        healthcheck:
            test: wget --spider http://localhost:7203/actuator/health || exit 1
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 20s
        environment:
            - domain.url=${DOMAIN_URL}
            - minio.url=${MINIO_URL}
            - minio.port=${MINIO_PORT}
            - minio.access_key=${MINIO_ACCESS_KEY}
            - minio.secret_key=${MINIO_SECRET_KEY}
            - postgres.url=${POSTGRES_URL}
            - postgres.database.name=${POSTGRES_DATABASE}
            - postgres.database.username=${POSTGRES_USERNAME}
            - postgres.database.password=${POSTGRES_PASSWORD}
        volumes:
            - ./volumes/logs/:/var/log/

    csv2rdf-converter-service:
        container_name: csv2rdf-converter-service
        image: schi11er/tt_csv2rdf-converter-service:latest
        restart: unless-stopped
        ports:
            - 7202:7202
        networks:
            - terraintwin_microservices
        depends_on:
            - configserver
            - eurekaserver
        healthcheck:
            test: wget --spider http://localhost:7202/actuator/health || exit 1
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s
        environment:
            - domain.url=${DOMAIN_URL}
            - minio.url=${MINIO_URL}
            - minio.port=${MINIO_PORT}
            - minio.access_key=${MINIO_ACCESS_KEY}
            - minio.secret_key=${MINIO_SECRET_KEY}
        volumes:
            - ./volumes/logs/:/var/log/

    gateway-service:
        container_name: gateway-service
        image: schi11er/tt_gateway-service:latest
        restart: unless-stopped
        ports:
            - 8084:8084
        networks:
            - terraintwin_microservices
        depends_on:
            - configserver
            - eurekaserver
        healthcheck:
            test: wget --spider http://localhost:8084/actuator/health || exit 1
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s
        environment:
            - domain.url=${DOMAIN_URL}
        volumes:
            - ./volumes/logs/:/var/log/

    admin-server:
        container_name: admin-server
        image: schi11er/tt_admin-server:latest
        restart: unless-stopped
        ports:
            - 9092:9092
        depends_on: 
            - eurekaserver
        networks:
            - terraintwin_microservices
        environment:
            - domain.url=${DOMAIN_URL}
        volumes:
            - ./volumes/logs/:/var/log/

    dashboard-service:
        container_name: dashboard-service
        image: schi11er/tt_dashboard-service:latest
        restart: unless-stopped
        ports:
            - 7205:7205
        networks:
            - terraintwin_microservices
        depends_on:
            - configserver
            - eurekaserver
        healthcheck:
            test: wget --spider http://localhost:7205/actuator/health || exit 1
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 20s
        environment:
            - domain.url=${DOMAIN_URL}
            - postgres.url=${POSTGRES_URL}
            - postgres.database.name=${POSTGRES_DATABASE}
            - postgres.database.username=${POSTGRES_USERNAME}
            - postgres.database.password=${POSTGRES_PASSWORD}
        volumes:
            - ./volumes/logs:/var/log

    topology-service:
        container_name: topology-service
        image: schi11er/tt_topology-service:latest
        restart: unless-stopped
        ports:
            - 7206:7206
        networks:
            - terraintwin_microservices
        depends_on:
            - configserver
            - eurekaserver
        healthcheck:
            test: wget --spider http://localhost:7206/actuator/health || exit 1
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 20s
        environment:
            - domain.url=${DOMAIN_URL}
            - postgres.url=${POSTGRES_URL}
            - postgres.database.name=${POSTGRES_DATABASE}
            - postgres.database.username=${POSTGRES_USERNAME}
            - postgres.database.password=${POSTGRES_PASSWORD}
        volumes:
            - ./volumes/logs:/var/log

    ifcterrain-service: 
        container_name: ifcterrain-service
        image: schi11er/tt_ifcterrain-service:latest
        restart: unless-stopped
        ports:
            - 7209:7209
        depends_on:
            - configserver
            - eurekaserver
        networks:
            - terraintwin_microservices
        environment:
            - domain.url=${DOMAIN_URL}
            - minio.url=${MINIO_URL}
            - minio.port=${MINIO_PORT}
            - minio.access_key=${MINIO_ACCESS_KEY}
            - minio.secret_key=${MINIO_SECRET_KEY}
        volumes:
            - ./volumes/files:/app/files
            - ./volumes/logs:/var/log

networks:
    terraintwin_microservices:
        driver: bridge