FROM alpine-jdk:base
COPY files/ConfigServer.jar /opt/lib/
RUN mkdir /var/lib/centralProperties
COPY centralProperties /var/lib/centralProperties
CMD ["java", "-jar", "/opt/lib/ConfigServer.jar"]
VOLUME /var/lib/centralProperties
EXPOSE 8888