Dockerfile-MinioUploadService 
================================
FROM alpine-jdk:base
COPY files/MinIOUploadService.jar /opt/lib/
CMD ["-jar", "/opt/lib/MinIOUploadService.jar"]
EXPOSE 7204

Dockerfile-GraphDBImportService
====================================
FROM alpine-jdk:base
COPY files/GraphDBImportService.jar /opt/lib/
CMD ["-jar", "/opt/lib/GraphDBImportService.jar"]
EXPOSE 7201

Dockerfile-PostgresImportService
=========================================
FROM alpine-jdk:base
COPY files/PostgresImportService.jar /opt/lib/
CMD ["-jar", "/opt/lib/PostgresImportService.jar"]
EXPOSE 7203

Dockerfile-Csv2RdfConverterService
=========================================
FROM alpine-jdk:base
COPY files/Csv2RdfConverterService.jar /opt/lib/
CMD ["-jar", "/opt/lib/Csv2RdfConverterService.jar"]
EXPOSE 7202

Dockerfile-GatewayService
=========================================
FROM alpine-jdk:base
COPY files/GatewayService.jar /opt/lib/
CMD ["-jar", "/opt/lib/GatewayService.jar"]
EXPOSE 8084