version: '3.8'
services:
    graphdb:
        image: ghcr.io/dd-bim/graphdb:9.4.1-free
        restart: unless-stopped
        ports:
            - ${GRAPHDB_PORT:-7200}:7200
        environment:
            GDB_JAVA_OPTS: >-
              -Xmx2g -Xms2g
              -Dgraphdb.home=/opt/graphdb/home
              -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
              -Dgraphdb.workbench.cors.enable=true
              -Denable-context-index=true
              -Dentity-pool-implementation=transactional
              -Dhealth.max.query.time.seconds=60
              -Dgraphdb.append.request.id.headers=true
              -Dreuse.vars.in.subselects=true
              -Dgraphdb.external-url=http://terrain.dd-bim.org/graphdb
        volumes:
            - ./volumes/graphdb:/opt/graphdb/home:Z

    postgres:
        image: postgis/postgis:13-3.0-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - ${POSTGRES_PORT:-5432}:5432
        volumes:
            - ./volumes/postgres:/var/lib/postgresql/data:Z

    minio:
        image: minio/minio:RELEASE.2020-11-12T22-33-34Z
        restart: unless-stopped
        ports:
            - ${MINIO_PORT:-9000}:9000
        environment:
            - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
            - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
        volumes:
            - ./volumes/minio:/data:Z
        command: ["server", "/data"]

    pgadmin:
        image: dpage/pgadmin4:5.3
        restart: unless-stopped
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USERMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        ports:
            - ${PGADMIN_PORT:-5433}:80
        volumes:
            # - ./volumes/pgadmin:/var/lib/pgadmin:Z
            - pgadmin:/var/lib/pgadmin

    geoserver:
        image: thinkwhere/geoserver:latest
        container_name: geoserver
        restart: unless-stopped
        ports: 
            - 8085:8080
        environment: 
            # - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
            # - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
            - GEOSERVER_LOG_LOCATION=/opt/geoserver/data_dir/logs/geoserver.log
        volumes: 
            - ./volumes/geoserver:/opt/geoserver/data_dir

volumes:
    pgadmin: