server:
    port: 8888
spring:
    application: 
        name: configserver
    cloud:
        config:
            server: 
                native:
                    search-locations: file:///D:/Git_Projekte/spring_boot_microservices/centralProperties
    profiles:
        active: native
    security:
        user:
            name: configserver
            password: s3cr3tconfigs