server:
    port: 8084

spring:
    cloud:
        gateway:
            routes:
                - id: graphdbimport-service
                  uri: lb://graphdb-import-service
                  predicates:
                      - Path=/graphdbimport/**
                - id: csv2rdf-service
                  uri: lb://csv2rdf-converter-service
                  predicates:
                      - Path=/csv2rdf/**
                - id: minioupload-service
                  uri: lb://minio-upload-service
                  predicates:
                      - Path=/minioupload/**
                - id: geometry-service
                  uri: lb://postgres-import-service
                  predicates:
                      - Path=/geometry/**
                - id: topology-service
                  uri: lb://topology-service
                  predicates:
                      - Path=/topology/**
                # - id: dashboard-service
                #   uri: lb://dashboard-service
                #   predicates:
                #       - Path=/postgresinfos/**
                - id: openapi
                  uri: http://localhost:${server.port}
                  predicates:
                      - Path=/terraintwin/v3/api-docs/**
                  filters:
                      - RewritePath=/terraintwin/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  api-docs: 
    path: /terraintwin/v3/api-docs
  swagger-ui: 
    path: /terraintwin/swagger-ui.html 
    operationsSorter: method

logging:
    file:
        name: /var/log/gateway-service.log

management:
    endpoint:
        logfile:
            external-file: /var/log/gateway-service.log