server:
    port: 8084

spring:
    cloud:
        gateway:
            routes:
                - id: inputhandler-service
                  uri: lb://file-input-handler
                  predicates:
                      - Path=/inputhandler/**
                - id: csv2rdf-service
                  uri: lb://csv2rdf-converter-service
                  predicates:
                      - Path=/csv2rdf/**
                - id: minioupload-service
                  uri: lb://minio-upload-service
                  predicates:
                      - Path=/minioupload/**
                - id: geometry-service
                  uri: lb://geometry-handler
                  predicates:
                      - Path=/geometry/**
                - id: topology-service
                  uri: lb://topology-service
                  predicates:
                      - Path=/topology/**
                - id: terraintoifc-service
                  uri: lb://ifcterrain-service
                  predicates:
                      - Path=/terraintoifc/**
                - id: ifccontourcreator-service
                  uri: lb://ifccontour-creator
                  predicates:
                      - Path=/ifccontourcreator/**
                - id: semanticconnector-service
                  uri: lb://semantic-connector
                  predicates:
                      - Path=/semanticconnector/**
                - id: querybimserver-service
                  uri: lb://bimserver-query-service
                  predicates:
                      - Path=/querybimserver/**
                - id: scheduler-service
                  uri: lb://scheduler-service
                  predicates:
                      - Path=/scheduler/**
                - id: openapi
                  uri: http://localhost:${server.port}
                  predicates:
                      - Path=/terraintwin/v3/api-docs/**
                  filters:
                      - RewritePath=/terraintwin/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  api-docs: 
    path: /terraintwin/v3/api-docs
  swagger-ui: 
    path: /terraintwin/swagger-ui.html 
    operationsSorter: method

logging:
    file:
        name: /var/log/gateway-service.log

management:
    endpoint:
        logfile:
            external-file: /var/log/gateway-service.log