eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eurekaserver:9091/eureka

logging:
    level: 
        root: INFO #  TRACE DEBUG INFO WARN ERROR