server:
    port: 7202
           
springdoc:
    api-docs:
        path: /csv2rdf/v3/api-docs
    swagger-ui: 
        path: /csv2rdf/swagger-ui.html
        operationsSorter: method

logging:
    file:
        name: /var/log/csv2rdf-converter-service.log

management:
    endpoint:
        logfile:
            external-file: /var/log/csv2rdf-converter-service.log