server:
    port: 7203

springdoc:
    api-docs:
        path: /geometry/v3/api-docs
    swagger-ui: 
        path: /geometry
        operationsSorter: method
        disable-swagger-default-url: true

spring:
    datasource:
        url: jdbc:postgresql://${postgres.url}/${postgres.database.name}
        username: ${postgres.database.username}
        password: ${postgres.database.password}
        platform: postgresql
        driver-class-name: org.postgresql.Driver
        initialization-mode: always

    jpa:
        show-sql: true
        open-in-view: false
        hibernate:
            ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
        properties:
            hibernate:
                generate_statistics: true
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                default_schema: terraintwinv2
    data:
        jpa:
            repositories:
                bootstrap-mode: default

logging:
    level:
        org:
            hibernate:
                stat: debug
                type: trace
    file:
        name: /var/log/geometry-handler.log

javax:
    persistence:
        create-database-schemas: true

management:
    endpoint:
        logfile:
            external-file: /var/log/geometry-handler.log