server:
    port: 7201
     
springdoc:
    api-docs:
        path: /graphdbimport/v3/api-docs
    swagger-ui: 
        path: /graphdbimport/swagger-ui.html
        operationsSorter: method

logging:
    file:
        name: /var/log/graphdb-import-service.log