server:
    port: 7209

springdoc:
    api-docs:
        path: /terraintoifc/v3/api-docs
    swagger-ui: 
        path: /terraintoifc/swagger-ui.html
        operationsSorter: method
        disable-swagger-default-url: true

logging:
    file:
        name: /var/log/ifcterrain-service.log

management:
    endpoint:
        logfile:
            external-file: /var/log/ifcterrain-service.log