server:
    port: 7204

springdoc:
    api-docs:
        path: /minioupload/v3/api-docs
    swagger-ui: 
        path: /minioupload/swagger-ui.html
        operationsSorter: method

logging:
    file: 
        name: /var/log/minio-upload-service.log
    pattern:
        file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management:
    endpoint:
        logfile:
            external-file: /var/log/minio-upload-service.log