server:
    port: 7206

springdoc:
    api-docs:
        path: /topology/v3/api-docs
    swagger-ui: 
        path: /topology
        operationsSorter: method
        url: /openapi.yml
        # configUrl: /openapi.yml

spring:
    datasource:
        url: jdbc:postgresql://${postgres.url}/${postgres.database.name}
        username: ${postgres.database.username}
        password: ${postgres.database.password}
        driver-class-name: org.postgresql.Driver
        initialization-mode: always

    jpa:
        show-sql: true
        open-in-view: false
        hibernate:
            ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
        properties:
            hibernate:
                generate_statistics: true
                format_sql: true
                dialect: 
                    - org.hibernate.dialect.PostgreSQL95Dialect
                    - org.hibernate.spatial.dialect.postgis.PostgisDialect
    data:
        jpa:
            repositories:
                bootstrap-mode: default

logging:
    level:
        org:
            hibernate:
                stat: debug
                type: trace
    file:
        name: /var/log/topology-service.log

javax:
    persistence:
        create-database-schemas: true

management:
    endpoint:
        logfile:
            external-file: /var/log/topology-service.log
