server:
    port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: API_Gateway
  cloud:
    gateway:
      routes:
      - id: dashboard
        uri: lb://EMPLOYEEDASHBOARD
        predicates:
        - Path=/dashboard/**
      - id: graphdbimport
        uri: lb://GRAPHDBIMPORTER
        predicates:
        - Path=/graphdbimport/**
      - id: csv2rdf
        uri: lb://CSV2RDFCONVERTER
        predicates:
        - Path=/csv2rdf/**