server:
    port: 8084

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: API_Gateway
  cloud:
    gateway:
      routes:
      - id: graphdbimport-service
        uri: lb://GRAPHDBIMPORTER
        predicates:
        - Path=/terraintwin/graphdbimport/**
      - id: csv2rdf-service
        uri: lb://CSV2RDFCONVERTER
        predicates:
        - Path=/terraintwin/csv2rdf/**
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /terraintwin/$\{path}/v3/api-docs

springdoc:
  api-docs: 
    path: /v3/api-docs
  swagger-ui: 
    path: /terraintwin/swagger-ui.html 
    operationsSorter: method



