spring:
  application:
    name: test-service
  profiles:
    active: prod
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      username: configserver
      password: s3cr3tconfigs